### ISSUE TITLE
Gobuster recursive mode

### ISSUE THREAD

**Issue by NinjaJc01** [zeMenno/lazy-hacker#1]
Automate gobuster recursion, so if you find a /admin dir it will scan that dir afterwards. Probably best to use a flag.

**Comment by zeMenno** [comment]
Do you think this works if i put it in a seperate script, or will people want it inside the same script?

**Comment by zeMenno** [comment]
Hi @NinjaJc01, i have added the feature you asked for. It's a bit slow but will do for now, can you test to see if it works as you imagined it?
